# docker-compose.yml
services:
  tiled:
    # image: ghcr.io/bluesky/tiled:0.1.0-b17
    build:
      context: ./tiled
      dockerfile: Dockerfile
    container_name: tiled_workflow_server
    command: bash -c "/app/tiled/tiled_config_serve_container.sh"
    volumes:
      - ./tiled:/app/tiled
      #- desy-drive:/data
      - .env:/deploy/.env
      - ${PATH_TO_RAW_DATA}:/data
    environment:
      PATH_TO_RAW_DATA: ${PATH_TO_RAW_DATA}
      TILED_API_KEY: ${TILED_API_KEY}
      PATH_TO_DATA_CATALOG: "/app/tiled/db/catalog_docker.db"
    depends_on:
      - tiled-watch
    ports:
      - '8888:8888'
    networks:
      - workflow_viz_default

  tiled-watch:
    image: workflow_viz
    # build this one, have the other depend on it
    build: .
    container_name: tiled_workflow_watcher
    command: bash -c "/app/tiled/tiled_catalog_register.sh"
    volumes:
      - ./tiled:/app/tiled
      # - .env:/app/.env
      #- data-drive:/data
      - /Users/dylanmcreynolds/data/tiled/raw:/data/raw
      - /Users/dylanmcreynolds/data/tiled/processed:/data/processed
    environment:
      PATH_TO_RAW_DATA: "/data/raw"
      PATH_TO_RAW_DATA_CATALOG: "/app/tiled/db/catalog_docker.db"
      PATH_TO_PROCESSED_DATA: "/data/processed"
      PATH_TO_PROCESSED_DATA_CATALOG: "/app/tiled/db/catalog_processed_docker.db"
      
    networks:
      - workflow_viz_default

  workflow-viz:
    image: workflow_viz
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workflow_viz
    command: 'python app.py'
    environment:
      TILED_API_KEY: ${TILED_API_KEY}
      TILED_URI: "http://tiled:8888"
      PREFECT_API_URL: "http://prefect-server:4200/api"
    volumes:
      - ./app.py:/app/app.py
      - ./callbacks:/app/callbacks
      - ./components:/app/components
      - ./utils:/app/utils
    ports:
      - '8095:8095'
    networks:
      - workflow_viz_default
  kvrocks:
    image: kvrocks/kvrocks:latest
    ports:
      - "6666:6666"
    networks:
      - workflow_viz_default
networks:
  workflow_viz_default:
    external: true
    #volumes:
    #desy-drive:
    #driver: local
    #driver_opts:
    #type: cifs
    # With full address
    #o: addr=****.desy.de,username=*******,password=*******,vers=3.0
    #device: //***.desy.de/**********/p03/2023/data\*******
    # With ip address
    #o: username=*******,password=*******,vers=3.0
    #device: //***.***.***.***/**********/p03/2023/data/*******
