# config.yml

file_extensions:
  edf: application/x-edf
  cbf: application/x-cbf
  fits: application/x-fits
  gb: application/x-gb

trees:
  - path: /raw
    tree: tiled.catalog:from_uri
    args:
      uri: $PATH_TO_RAW_DATA_CATALOG
      readable_storage: [$PATH_TO_RAW_DATA]
      init_if_not_exists: true
      adapters_by_mimetype: 
        application/x-cbf: custom.cbf:read
        application/x-edf: custom.edf:read
        application/x-fits: custom.fits:read
        application/x-gb: custom.gb:read
        multipart/related;type=application/x-hdf5: custom.lambda_nxs:read_sequence
  - path: /processed
    tree: tiled.catalog:from_uri
    args:
      uri: $PATH_TO_PROCESSED_DATA_CATALOG
      writable_storage: $PATH_TO_PROCESSED_DATA
      readable_storage: [$PATH_TO_PROCESSED_DATA]
      init_if_not_exists: true
      adapters_by_mimetype: 
        application/x-cbf: custom.cbf:read
        application/x-edf: custom.edf:read
        application/x-fits: custom.fits:read
        application/x-gb: custom.gb:read
        multipart/related;type=application/x-hdf5: custom.lambda_nxs:read_sequence


uvicorn:
  host: 127.0.0.1
  port: 8888


authentication:
  # For local testing allow anonymous access
  allow_anonymous_access: true
  single_user_api_key: $TILED_API_KEY

allow_origins:
  - http://127.0.0.1:8050
  - http://localhost:8050
  - http://127.0.0.1:8095
  - http://localhost:8095


